## Numpy Array Operations

In [2]:
import numpy as np

In [4]:
arr = np.arange(12)
print("Basic slicing",arr[2:7])
print("with setp  slicing",arr[1:7:2])
print("Negative slicing",arr[-4])


Basic slicing [2 3 4 5 6]
with setp  slicing [1 3 5]
Negative slicing 8


In [6]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("arr_2d",arr_2d)
print("Specific Element",arr_2d[2,2])
print("Entire row",arr_2d[0])
print("Entire Col",arr_2d[:,0])

arr_2d [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific Element 9
Entire row [1 2 3]
Entire Col [1 4 7]


## Sorting

In [10]:
unsorted  =np.array([1,2,3,8,6,7,5,94,3,62,1,5,7])
print("Sorted Array",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[3,2],[2,1]])
print("Sorted 2D  Array by col",np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D  Array by row",np.sort(arr_2d_unsorted, axis=1))

Sorted Array [ 1  1  2  3  3  5  5  6  7  7  8 62 94]
Sorted 2D  Array by col [[2 1]
 [3 1]
 [3 2]]
Sorted 2D  Array by row [[1 3]
 [2 3]
 [1 2]]


## Filtering

In [18]:
number  =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("number",number)

even_number = number[number%2==0]
print("even_number",even_number)

number [ 1  2  3  4  5  6  7  8  9 10 11 12]
even_number [ 2  4  6  8 10 12]


## Filter with mask

In [14]:
mask = number %3 == 0
print("number greater than  5",number[mask])

number greater than  5 [0 3 6 9]


## Fancy indexing vs np.where()

In [21]:
indices = [0,2,4]
print(number[indices])

where_result = np.where(number>5)
print("indexes of number",where_result)
print("NP where", number[where_result])

[1 3 5]
indexes of number (array([ 5,  6,  7,  8,  9, 10, 11]),)
NP where [ 6  7  8  9 10 11 12]


In [27]:
condition_array =np.where(number>7,number+1,number)
print(condition_array)

[ 1  2  3  4  5  6  7  9 10 11 12 13]


## Adding and Removing Data

In [29]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1+arr2
print("this is how the arrays are added",combined)

combine  =np.concatenate((arr1, arr2))
print(" this is how combine the array",combine)

this is how the arrays are added [5 7 9]
 this is how combine the array [1 2 3 4 5 6]


## Array Compatiblity

In [30]:
a  = np.array([1,2,3])
b  = np.array([4,5,6])
c  = np.array([7,8,9])

print("compatiblity shapes",a.shape == b.shape == c.shape)

compatiblity shapes True


In [33]:
old_Array = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row =np.vstack((old_Array,new_row))

print(old_Array)
print(with_new_row)

new_col =np.array([[7],[8]])
with_new_col =np.hstack((old_Array,new_col))
print(with_new_col)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


# Delete array

In [34]:
arr =np.array([1,2,3,45,6,7,8,9])
deleted  =np.delete(arr,4)
print("Array after deletion",deleted)

Array after deletion [ 1  2  3 45  7  8  9]
