# NUmpy Array and Basics

In [2]:
import numpy as np

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", arr_2d)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## List vs Numpy  array

In [ ]:
py_list = [1, 2, 3, 4, 5]
print("Python List multiplication:", py_list*2)

np_array = np.array([1, 2, 3, 4, 5])
print("Python List multiplication:", np_array*2)

print("Numpy arrays are faster than Python lists for large data sets.")

Python List multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Python List multiplication: [ 2  4  6  8 10]


## Creating Array From Scratch

In [6]:
zeros = np.zeros((3, 4))
print("Zeros Array:\n", zeros)

one = np.ones((2, 3))
print("Ones Array:\n", one)

full = np.full((2, 3), 7)
print("Full Array:\n", full)

random  = np.random.random((2, 3))
print("Random Array:\n", random)

sequence = np.arange(0, 10, 2)
print("Sequence Array:", sequence)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array:
 [[7 7 7]
 [7 7 7]]
Random Array:
 [[0.39272979 0.89816818 0.84878642]
 [0.42828738 0.23506734 0.57105605]]
Sequence Array: [0 2 4 6 8]


## Vector,Matrix,Tensor

In [9]:
vector = np.array([1,2,3,4,5])
print("Vector Array:", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix Array:\n", matrix)

tensor =np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor Array:\n", tensor)



Vector Array: [1 2 3 4 5]
Matrix Array:
 [[1 2 3]
 [4 5 6]]
Tensor Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Arrays properties

In [10]:
arr =np.array([[1, 2, 3], [4, 5, 6]])
print( "Array Shape:", arr.shape)
print("Array Dimension:", arr.ndim)
print("Array Size:", arr.size)
print("Array Data Type:", arr.dtype)

Array Shape: (2, 3)
Array Dimension: 2
Array Size: 6
Array Data Type: int64


## Array Reshaping

In [16]:
arr =np.arange(12)
print("Original Array:\n", arr)

reshape = arr.reshape(3,4)
print("Reshaped Array:\n", reshape)

flattened = reshape.flatten()
print("Flattened Array:\n", flattened)

# ravel (returns view , not copy)
ravled = reshape.ravel()
print("Raveled Array:\n", ravled)

#Transpose
transposed = reshape.T 
print("Transposed Array:\n", transposed)

Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
